services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: airbook
      POSTGRES_USER: airbook
      POSTGRES_PASSWORD: airbook123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  frontend:
    build: ./frontend/airbook-ui
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
